### ISSUE TITLE
CCE cluster namespace info cannot be loaded into the plugin

### ISSUE THREAD

**Issue by paulmchen** [CPE-OAuth/servicestage-eclipse-plugin#5]
from ServiceStage plugin, i configure the app by bringing up the app configure panel. When i select a cce cluster and then choose its namespace from the list, i received errors and indicate that the namespace is invalid.

(see the attached the screen)

**Comment by paulmchen** [comment]
![ccenamespace-issues](https://user-images.githubusercontent.com/32553156/49325080-f8a6ec80-f509-11e8-9f95-89432d9e5f40.PNG)

**Comment by paulmchen** [comment]
When i checked it from the servicestage console from Huawei cloud, i do see the "default" namespace associated with this given CCE cluster.

**Comment by paulmchen** [comment]
The following error message indicates that CCE api had been recently changed and enabled for the host site of validation.  dc55-11e8-8e91-0255ac101f09.cce.cn-north-1.myhuaweicloud.com failed on validation against *.cn-north-1.myhuaweicloud.com  due to the cce subdomain in the URI.


See details
  javax.net.ssl.SSLPeerUnverifiedException: Certificate for <e742314c-dc55-11e8-8e91-0255ac101f09.cce.cn-north-1.myhuaweicloud.com> doesn't match any of the subject alternative names: [*.cn-north-1.myhuaweicloud.com]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:467)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.huawei.cloud.servicestage.client.HuaweiCloudClient.performGet(HuaweiCloudClient.java:58)
	at com.huawei.cloud.servicestage.client.HuaweiCloudClient.getNamespaces(HuaweiCloudClient.java:279)
	at com.huawei.cloud.servicestage.eclipse.RequestManager.getNamespaces(RequestManager.java:366)
	at com.huawei.cloud.servicestage.eclipse.AppConfigWizardPage.lambda$2(AppConfigWizardPage.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:180)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)

**Comment by paulmchen** [comment]
Tried with the Postman and having the same problem. It is an CCE issue just happened no more than a day ago.

**Comment by paulmchen** [comment]
![postman error screen](https://user-images.githubusercontent.com/32553156/49335326-59d9c900-f5b9-11e8-9a65-4f897f0f05c1.PNG)

**Comment by paulmchen** [comment]
@ewcchan have you ever seeing this issue when you are working on the current feature in this project? Thanks.

**Comment by ewcchan** [comment]
@paulmchen I didn’t see the issue when I tried; however I added accept all certificate settings in the common clients code that should have taken care of the SSL issue mentioned above in the exception.

**Comment by paulmchen** [comment]
This problem goes away now.
